### ISSUE TITLE
Fail stripping in: data.viewing.substr(data.viewing.indexOf('://') + 3)

### ISSUE THREAD

**Issue by liesislukas** [RnbWd/gulp-strip-comments#5]
if i use: 

```
.pipe(strip({
      line: true,
      first: false,
      block: false,
      safe: true,
    }))
```

it fails to strip on this line:

```
data.viewing.substr(data.viewing.indexOf('://') + 3)
```

it thinks it is comment in the end, as you can see it's not.

if i use: 

```
.pipe(strip({
      line: false,
      first: false,
      block: true,
      safe: true,
    }))
```

it ends with "Segmentation fault: 11" 

I have 2.7MB Js file to minify. ~80 000 lines of magic.

**Comment by RnbWd** [comment]
I reverted the library back to the API before the `strip-comments` repo changed it's methods - is this issue related to the new changes?

**Comment by liesislukas** [comment]
I've used this lib once, it failed and i haven't tried it more, so can't tell.

**Comment by vitaly-t** [comment]
@liesislukas if you still need a proper comment stripping functionality [decomment](https://github.com/vitaly-t/decomment) library does it properly ;)

**Comment by liesislukas** [comment]
@vitaly-t  thanks, i will try it out :+1:

**Comment by RnbWd** [comment]
FYI this library is just a wrapper around another library (that I actually want to remove). There weren't other options avail. at the time and no plugins in the gulp ecosystem.

@vitaly-t I like your implementation much better - I noticed you published a gulp-plugin and are seeking help - I think we can work together. Gulp encourages utilizing one library for one task, so having one plugin for 'decommenting' or 'stripping comments' - becoming the best library possible for the task is best I think. I'll comment on your repo to continue discussion. 

@liesislukas I  use module called `gulp-tap` to customize my builds instead of relying on lame plugin maintainers (like myself :stuck_out_tongue_closed_eyes: ). Something like this:

```js
var gulp = require('gulp');
var tap = require('gulp-tap');
var decomment = require('decomment');

gulp.task('decomment', function() {
   return  gulp.src(paths)
        .pipe(tap(function(file) {
           // I haven't tested this
           var contents = decomment(file.contents.toString());
           file.contents = new Buffer(contents)
        }))

  })
})
```

Something like that I think. I've used this pattern in production with [file-indexer](https://github.com/rnbwd/file-indexer)

**Comment by RnbWd** [comment]
try now? I just updated the library (using `decomment`)

**Comment by liesislukas** [comment]
decomment was not helping either. Finally found great solution to minimize my crazy 85000 lines codebase. Maybe it would suite for smaller projects.

Used this one:
https://developers.google.com/closure/compiler/

this link helped to form actual command:
https://developers.google.com/closure/compiler/docs/compilation_levels?csw=1

this is what i used:

```
java -jar compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js ./public_static/build/client.js > client.min.js
```
During these 18 days i wrote ~5000 lines more, so now i have 3MB file for production.
After compiler.jar i have 1.2MB with SIMPLE_OPTIMIZATIONS 0.9MB with ADVANCED_OPTIMIZATIONS but it also produced some errors, so sticked with SIMPLE_OPTIMIZATIONS.

hope that will help someone :+1:

**Comment by vitaly-t** [comment]
@liesislukas could you, please, elaborate, what was the problem with decomment?

>decomment was not helping either.

**Comment by liesislukas** [comment]
@vitaly-t i have moved on, but you can try something with React and jsx to check

https://github.com/facebook/react/wiki/Examples

**Comment by vitaly-t** [comment]
@liesislukas if you can give an example of where decomment didn't work as expected, that would be helpful. Suggesting that I would come up with an example myself isn't how these issues are resolved.

I am therefore inclined to close the issue, as we are not making any progress here. If you get back to us with an example, we will re-open it.
