### ISSUE TITLE
note: crashes on JSX files. for now gulp strip must take place after gulp-babel

### ISSUE THREAD

**Issue by PrimeLens** [RnbWd/gulp-strip-comments#9]
note: crashes on JSX files. for now gulp strip must take place after gulp-babel

**Comment by PrimeLens** [comment]
error log shows
```
            throw e;
                  ^
Error: Line 20: Invalid regular expression: missing /
```

**Comment by vitaly-t** [comment]
@PrimeLens Could you, please show what's on Line 20 that's recognized as invalid?

**Comment by PrimeLens** [comment]
the following JSX file crashes if you strip comments before gulp-babel but passes fine if you strip comments after gulp-babel

```
rc.myPageComponent = React.createClass({
    getInitialState:function(){
        return {}
    },
    render: function() {
        var renderHandle;
        var completedPreload = true;
        if (!completedPreload) {
            renderHandle = <div id="mypage"></div>
        } else {
            renderHandle =             
            <div id="mypage">   
                <p>
                    This page gives an example of how the lorem ipsum works in conjunction with the lorem ipsum library.
                </p>
            </div>    
        }
        return(
            renderHandle
        );
    }
});
```

**Comment by vitaly-t** [comment]
This thing: `renderHandle = <div id="mypage"></div>` is absolutely not a valid JavaScript at all. If Babel allows something like this, you JavaScript parsing of this library. This library only supports ES6-compliant JavaScript, as per [decomment](https://github.com/vitaly-t/decomment) documentation.

You have 2 choices here:

1.  Translate your code into ES6-compliant JavaScript first;
2. Decomment your code as a text instead.

The second one means that instead of calling `decomment`, call `decomment.text`, which will disable any JavaScript parsing. Just beware that should your code have some special regular expressions in it, it may not process them correctly.

**Comment by PrimeLens** [comment]
yes thats what i said in the subject line of the issue, to translate first.  Since React JSX is so popular right now why don't you call out React specifically in the docs?

**Comment by vitaly-t** [comment]
Did it work for you with `decomment.text`?
